apiVersion: v1
kind: Namespace
metadata:
  name: istio-stuff
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask
  namespace: istio-stuff
---
apiVersion: v1
kind: Service
metadata:
  name: flask
  labels:
    app: flask
  namespace: istio-stuff
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 5000
  selector:
    app: flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: istio-stuff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
      version: v1
  template:
    metadata:
      labels:
        app: flask
        version: v1
    spec:
      serviceAccountName: flask
      containers:
      - image: ozrlz/flask-client:k8s
        imagePullPolicy: IfNotPresent
        name: flask
        ports:
        - containerPort: 5000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: flask-gateway
  namespace: istio-stuff
spec:
  selector:
    istio: ingressgateway # use istio default ingress gateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "flask.ozrlz.com"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask
  namespace: istio-stuff
spec:
  hosts:
  - "flask.ozrlz.com"
  gateways:
  - flask-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        port:
          number: 8000
        host: flask
