{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
apiVersion: v1
kind: Service
metadata:  
  name: ingress-gateway-np
  namespace: {{ .Release.Namespace }}
  labels:
    app: ing-gw-np
    release: {{ .Release.Name }}
    kinda: ing-gw-np
spec:
  type: NodePort
  selector:    
    app: istio-ingressgateway
    istio: ingressgateway
  ports:  
  - name: http
    port: 80
    targetPort: 80
  - name: healthcheck
    port: 15020
    targetPort: 15020
    nodePort: 30020